class CreateNotifications < ActiveRecord::Migration[8.1]
  # Phase 9.6 sub-area #6 — Notification System.
  #
  # A single notifications table powers the bell dropdown in the
  # navbar. Each row is a user-facing event generated by the app:
  # appointment created / cancelled / confirmed, patient created,
  # new conversation, etc.
  #
  # Subject references are explicit nullable FKs rather than a
  # polymorphic association so we keep real database foreign keys
  # (and `ON DELETE SET NULL` / restrict behaviour later if needed).
  # The set of subject tables is small and stable — polymorphic adds
  # cost without a real upside here.
  def change
    create_table :notifications do |t|
      t.string :category, null: false
      t.string :level, null: false, default: "info"
      t.string :title, null: false
      t.text   :body
      t.string :url
      t.datetime :read_at

      # Optional subject references — a notification is always about
      # one of these, but we leave them independently nullable so the
      # service layer can emit "system" events later without a
      # subject row to hang off.
      t.references :patient,      foreign_key: true, null: true
      t.references :appointment,  foreign_key: true, null: true
      t.references :conversation, foreign_key: true, null: true

      t.timestamps
    end

    # The dropdown's two primary queries — "latest N notifications"
    # and "how many are unread" — both benefit from an index on
    # (read_at, created_at). Partial index keeps it tight since the
    # unread subset is what gets hit most often.
    add_index :notifications, :created_at
    add_index :notifications, :read_at, where: "read_at IS NULL", name: "index_notifications_on_unread"
    add_index :notifications, :category
  end
end
